### ISSUE TITLE
Consider enabling CORS 

### ISSUE THREAD

**Issue by codymikol** [Neuman968/pasteybin#1]
Hey man, cool project.

Would you accept a PR to re-enable CORS? I think having this disabled by default could lead to some cross-origin naughtiness inadvertently allowing arbitrary websites to fill up your pasteybin database

**Comment by codymikol** [comment]
Was thinking about throwing this up on my digitalocean box this weekend

**Comment by Neuman968** [comment]
@codymikol Thanks dude! good call on cors. The allowed hosts could probably be injected via environment variables to the container so that way it is not hard coded into the image. I'd definitely accept P.R's!
